/*********************************************
16-bit RGB Colour Definitions
See "colors.pdf" for illustration
*********************************************/

#ifndef _COLORS_H_
#define _COLORS_H_

#define WHITE      				0xffff
#define SNOW      				0xffde
#define GHOSTWHITE      		0xf7bf
#define IVORY      				0xfffd
#define MINTCREAM      			0xf7fe
#define AZURE      				0xefff
#define FLORALWHITE      		0xffdd
#define ALICEBLUE      			0xefbf
#define LAVENDERBLUSH      		0xff7e
#define SEASHELL      			0xffbd
#define WHITESMOKE      		0xf7be
#define HONEYDEW      			0xeffd
#define LIGHTYELLOW      		0xfffb
#define LIGHTCYAN      			0xdfff
#define OLDLACE      			0xffbc
#define CORNSILK      			0xffbb
#define LINEN      				0xf77c
#define LEMONCHIFFON      		0xffd9
#define LIGHTGOLDENRODYELLOW    0xf7d9
#define BEIGE      				0xf7bb
#define LAVENDER      			0xe73e
#define MISTYROSE      			0xff1b
#define PAPAYAWHIP      		0xff7a
#define ANTIQUEWHITE      		0xf75a
#define BLANCHEDALMOND      	0xff59
#define BISQUE      			0xff18
#define MOCCASIN      			0xff16
#define GAINSBORO      			0xdedb
#define PEACHPUFF      			0xfed6
#define PALETURQUOISE      		0xaf7d
#define NAVAJOWHITE      		0xfef5
#define PINK      				0xfdf9
#define WHEAT      				0xf6f6
#define PALEGOLDENROD      		0xef34
#define LIGHTGREY      			0xd69a
#define LIGHTPINK      			0xfdb7
#define POWDERBLUE      		0xaefc
#define THISTLE      			0xd5fa
#define LIGHTBLUE      			0xaebc
#define KHAKI      				0xef31
#define VIOLET      			0xec1d
#define PLUM      				0xdcfb
#define LIGHTSTEELBLUE      	0xae1b
#define AQUAMARINE      		0x7ffa
#define LIGHTSKYBLUE      		0x867e
#define SILVER      			0xbdf7
#define SKYBLUE      			0x867d
#define PALEGREEN      			0x97d2
#define ORCHID      			0xd37a
#define BURLYWOOD      			0xddb0
#define HOTPINK      			0xfb56
#define LIGHTSALMON      		0xfcee
#define TAN      				0xcd91
#define LIGHTGREEN      		0x8f71
#define YELLOW      			0xffe0
#define FUCHSIA      			0xf81f
#define MAGENTA      			0xf81f
#define AQUA      				0x07ff
#define CYAN      				0x07ff
#define DARKGRAY      			0xa554
#define DARKSALMON      		0xe4ae
#define SANDYBROWN      		0xf50b
#define LIGHTCORAL      		0xebef
#define TURQUOISE      			0x3ef9
#define SALMON      			0xf3ed
#define CORNFLOWERBLUE      	0x64bd
#define MEDIUMTURQUOISE      	0x4699
#define MEDIUMORCHID      		0xb2ba
#define DARKKHAKI      			0xbdad
#define PALEVIOLETRED      		0xdb72
#define MEDIUMPURPLE      		0x937b
#define MEDIUMAQUAMARINE      	0x6674
#define GREENYELLOW      		0xafe5
#define ROSYBROWN      			0xbc71
#define DARKSEAGREEN      		0x8dd1
#define GOLD      				0xfea0
#define MEDIUMSLATEBLUE      	0x7b3d
#define CORAL      				0xfbe9
#define DEEPSKYBLUE      		0x05ff
#define DODGERBLUE      		0x1c7f
#define TOMATO      			0xfb08
#define DEEPPINK      			0xf892
#define ORANGE      			0xfd20
#define GOLDENROD      			0xd523
#define DARKTURQUOISE      		0x0679
#define CADETBLUE      			0x5cf3
#define YELLOWGREEN      		0x9665
#define LIGHTSLATEGRAY      	0x7432
#define DARKORCHID      		0x9199
#define BLUEVIOLET      		0x815b
#define MEDIUMSPRINGGREEN      	0x07d2
#define PERU      				0xcc27
#define SLATEBLUE      			0x62d9
#define DARKORANGE      		0xfc40
#define ROYALBLUE      			0x3b5b
#define INDIANRED      			0xcacb
#define GRAY      				0x7bef
#define SLATEGRAY      			0x6bf1
#define CHARTREUSE      		0x7fe0
#define SPRINGGREEN      		0x07ef
#define STEELBLUE      			0x4416
#define LIGHTSEAGREEN      		0x1d94
#define LAWNGREEN      			0x7fc0
#define DARKVIOLET      		0x901a
#define MEDIUMVIOLETRED      	0xc0b0
#define MEDIUMSEAGREEN      	0x3d8d
#define CHOCOLATE      			0xcb43
#define DARKGOLDENROD      		0xb421
#define ORANGERED      			0xfa20
#define DIMGRAY      			0x634c
#define LIMEGREEN      			0x2e65
#define CRIMSON      			0xd887
#define SIENNA      			0x9a85
#define OLIVEDRAB      			0x6c64
#define DARKMAGENTA      		0x8811
#define DARKCYAN      			0x0451
#define DARKSLATEBLUE      		0x41f1
#define SEAGREEN      			0x2c4a
#define OLIVE      				0x7be0
#define PURPLE      			0x780f
#define TEAL      				0x03ef
#define RED      				0xf800
#define LIME      				0x07e0
#define BLUE      				0x001f
#define BROWN      				0xa144
#define FIREBRICK      			0xa903
#define DARKOLIVEGREEN      	0x5345
#define SADDLEBROWN      		0x8a22
#define FORESTGREEN      		0x1c43
#define INDIGO      			0x480f
#define DARKSLATEGRAY      		0x2a69
#define MEDIUMBLUE      		0x0019
#define MIDNIGHTBLUE      		0x10cd
#define DARKRED      			0x8800
#define DARKBLUE      			0x0011
#define MAROON      			0x7800
#define GREEN      				0x03e0
#define NAVY      				0x000f
#define DARKGREEN      			0x0300
#define BLACK      				0x0000

#endif
